In [1]:
import pandas as pd
import numpy as np

# Основная таблица с сотрудниками
df = pd.DataFrame({
    'emp_id': [101, 102, 103, 104, 105, 106, 107, 108],
    'name': ['Анна', 'Борис', 'Виктор', 'Галина', 'Дмитрий', 'Елена', 'Жанна', 'Захар'],
    'dept': ['IT', 'Sales', 'IT', 'HR', 'Sales', 'IT', 'HR', 'Sales'],
    'salary': [60000, 75000, 80000, 70000, 65000, 82000, 72000, 68000],
    'age': [25, 30, 35, 42, 28, 31, 29, 33],
    'hours': [120, 80, 150, 90, 60, 130, 110, 95],
    'city': ['Москва', 'СПб', 'Москва', 'Казань', 'СПб', 'Москва', 'Казань', 'СПб']
})

# Вторая таблица для merge
bonuses = pd.DataFrame({
    'dept': ['IT', 'Sales', 'HR', 'Marketing'],
    'bonus_percent': [0.2, 0.15, 0.1, 0.25]
})

# Третья таблица для merge
projects = pd.DataFrame({
    'emp_id': [101, 102, 103, 104, 105, 106, 107, 101, 103],
    'project': ['P1', 'P2', 'P3', 'P1', 'P2', 'P3', 'P4', 'P4', 'P1'],
    'project_hours': [120, 80, 150, 90, 60, 130, 110, 70, 140]
})

In [6]:
df['new'] = df.groupby('dept')['salary'].transform('rank', ascending=False)

df[df['new'] == 1]

   emp_id   name   dept  salary  age  hours    city  new
1     102  Борис  Sales   75000   30     80     СПб  1.0
5     106  Елена     IT   82000   31    130  Москва  1.0
6     107  Жанна     HR   72000   29    110  Казань  1.0

In [3]:
df.groupby('dept').apply(lambda x: x.nlargest(1, 'salary')).reset_index(drop=True)

   emp_id   name  salary  age  hours    city  new
0     107  Жанна   72000   29    110  Казань  2.0
1     106  Елена   82000   31    130  Москва  3.0
2     102  Борис   75000   30     80     СПб  3.0

In [14]:
df.drop_duplicates('name')

   emp_id     name   dept  salary  age  hours    city  new
0     101     Анна     IT   60000   25    120  Москва  3.0
1     102    Борис  Sales   75000   30     80     СПб  1.0
2     103   Виктор     IT   80000   35    150  Москва  2.0
3     104   Галина     HR   70000   42     90  Казань  2.0
4     105  Дмитрий  Sales   65000   28     60     СПб  3.0
5     106    Елена     IT   82000   31    130  Москва  1.0
6     107    Жанна     HR   72000   29    110  Казань  1.0
7     108    Захар  Sales   68000   33     95     СПб  2.0